# Generated by Django 5.1.3 on 2024-11-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_g_winder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='g_winder',
            old_name='img',
            new_name='im',
        ),
    ]
