# Generated by Django 5.1.3 on 2024-11-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_g_reserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='g_reserved',
            old_name='reserve',
            new_name='reserved',
        ),
    ]
