# Generated by Django 5.1.3 on 2024-11-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_rename_reserve_g_reserved_reserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='g_reserved',
            old_name='reserved',
            new_name='re',
        ),
    ]
