# Generated by Django 5.1.3 on 2024-11-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0022_kodaikannal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kodaikannal',
            new_name='Kodaikanal',
        ),
        migrations.RenameField(
            model_name='kodaikanal',
            old_name='Kodaikannal',
            new_name='Kodaikanal',
        ),
    ]
