# Generated by Django 5.1.3 on 2024-11-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0024_rename_kodaikanal_kodai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kodai',
            old_name='Kodai',
            new_name='kodai',
        ),
    ]
