# Generated by Django 5.1.3 on 2024-11-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0025_rename_kodai_kodai_kodai'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kodai',
            new_name='Ko',
        ),
        migrations.RenameField(
            model_name='ko',
            old_name='kodai',
            new_name='ko',
        ),
    ]
