# Generated by Django 5.1.3 on 2024-11-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0031_tailand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Australia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('australia', models.ImageField(upload_to='pic')),
                ('plan', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
    ]
