# Generated by Django 5.1.3 on 2024-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0032_australia'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='plan',
            field=models.CharField(default='basic', max_length=100),
        ),
    ]
