# Generated by Django 5.1.3 on 2024-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0034_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='date_registered',
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(default=91, max_length=15),
        ),
    ]
