# Generated by Django 5.1.3 on 2024-11-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0038_alter_register_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
