# Generated by Django 5.1.3 on 2024-11-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0041_alter_register_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Phone_Number',
        ),
    ]
