# Generated by Django 5.1.3 on 2024-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0042_remove_register_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Phone_Number',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='Confirm_Password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='Password',
            field=models.CharField(max_length=15),
        ),
    ]
