# Generated by Django 5.1.3 on 2024-11-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0043_register_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Phone_Number',
        ),
    ]
