# Generated by Django 5.1.3 on 2024-11-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0044_remove_register_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Confirm_Password',
        ),
    ]
