# Generated by Django 5.1.3 on 2024-11-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0045_remove_register_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Password',
        ),
    ]
