# Generated by Django 5.1.3 on 2024-11-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0046_remove_register_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='User_Name',
        ),
    ]
