# Generated by Django 5.1.3 on 2024-11-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0047_remove_register_email_remove_register_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
