# Generated by Django 5.1.3 on 2024-11-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0048_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.CharField(max_length=50)),
                ('User_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.BigIntegerField(blank=True, default=None, null=True)),
                ('Password', models.CharField(max_length=15)),
                ('Confirm_Password', models.CharField(max_length=15)),
            ],
        ),
    ]
