# Generated by Django 5.1.3 on 2024-11-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0049_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='RegistrationForm',
        ),
    ]
