# Generated by Django 5.1.3 on 2024-11-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0052_book_now_delete_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_now',
            new_name='Book',
        ),
    ]
