# Generated by Django 5.1.3 on 2024-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0053_rename_book_now_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
