# Generated by Django 5.1.3 on 2024-11-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0055_alter_image_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
