# Generated by Django 5.1.3 on 2024-11-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0056_alter_image_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='g_winder',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
