# Generated by Django 5.1.3 on 2024-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0059_g_reserved_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='andaman',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='australia',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='east',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='europe',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='honeymoon',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='india',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='italy',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kerala',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kodai',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manali',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='munnar',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='north',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ooty',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paris',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shimla',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='south',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tailand',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
