# Generated by Django 5.1.3 on 2024-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0060_andaman_price_australia_price_east_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Phone_Number', models.BigIntegerField(blank=True, default=None, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
