# Generated by Django 5.1.3 on 2024-11-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0061_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('place1', models.CharField(max_length=20)),
                ('place2', models.CharField(max_length=20)),
                ('place3', models.CharField(max_length=20)),
                ('place4', models.CharField(max_length=20)),
                ('place5', models.CharField(max_length=20)),
                ('place6', models.CharField(max_length=20)),
                ('place7', models.CharField(max_length=20)),
                ('place8', models.CharField(max_length=20)),
                ('main_img', models.ImageField(upload_to='pic')),
                ('place9', models.CharField(max_length=20)),
                ('place10', models.TextField()),
                ('place11', models.CharField(max_length=20)),
                ('place12', models.TextField()),
                ('place13', models.CharField(max_length=20)),
                ('place14', models.TextField()),
                ('place15', models.CharField(max_length=20)),
                ('place16', models.TextField()),
                ('place17', models.CharField(max_length=20)),
                ('place18', models.TextField()),
                ('place19', models.CharField(max_length=20)),
                ('place20', models.TextField()),
                ('place21', models.CharField(max_length=20)),
                ('place22', models.TextField()),
                ('place23', models.CharField(max_length=20)),
                ('place24', models.TextField()),
                ('place25', models.CharField(max_length=20)),
                ('place26', models.TextField()),
                ('place27', models.CharField(max_length=20)),
                ('place28', models.TextField()),
                ('place29', models.CharField(max_length=20)),
                ('place30', models.TextField()),
                ('place31', models.CharField(max_length=20)),
                ('place32', models.TextField()),
            ],
        ),
    ]
