# Generated by Django 5.1.3 on 2024-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0062_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='place10',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place11',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place12',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place13',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place14',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place15',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place16',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place17',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place18',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place19',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place20',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place21',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place22',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place23',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place24',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place25',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place26',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place27',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place28',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place29',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place30',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place31',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='place32',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='place9',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
