# Generated by Django 5.1.3 on 2024-12-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0063_alter_details_place10_alter_details_place11_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('place1', models.CharField(max_length=20)),
                ('place2', models.CharField(max_length=20)),
                ('place3', models.CharField(max_length=20)),
                ('place4', models.CharField(max_length=20)),
                ('place5', models.CharField(max_length=20)),
                ('place6', models.CharField(max_length=20)),
                ('place7', models.CharField(max_length=20)),
                ('place8', models.CharField(max_length=20)),
                ('main_img', models.ImageField(upload_to='pic')),
                ('place9', models.CharField(default='name', max_length=200)),
                ('place10', models.TextField(default='name')),
                ('place11', models.CharField(default='name', max_length=200)),
                ('place12', models.TextField(default='name')),
                ('place13', models.CharField(default='name', max_length=200)),
                ('place14', models.TextField(default='name')),
                ('place15', models.CharField(default='name', max_length=200)),
                ('place16', models.TextField(default='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='place17',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place18',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place19',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place20',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place21',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place22',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place23',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place24',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place25',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place26',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place27',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place28',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place29',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place30',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place31',
        ),
        migrations.RemoveField(
            model_name='details',
            name='place32',
        ),
    ]
