# Generated by Django 5.1.3 on 2024-12-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0064_details1_remove_details_place17_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='i_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('place1', models.CharField(max_length=20)),
                ('place2', models.CharField(max_length=20)),
                ('place3', models.CharField(max_length=20)),
                ('place4', models.CharField(max_length=20)),
                ('place5', models.CharField(max_length=20)),
                ('place6', models.CharField(max_length=20)),
                ('place7', models.CharField(max_length=20)),
                ('place8', models.CharField(max_length=20)),
                ('main_img', models.ImageField(upload_to='pic')),
                ('place9', models.CharField(default='name', max_length=200)),
                ('place10', models.TextField(default='name')),
                ('place11', models.CharField(default='name', max_length=200)),
                ('place12', models.TextField(default='name')),
                ('place13', models.CharField(default='name', max_length=200)),
                ('place14', models.TextField(default='name')),
                ('place15', models.CharField(default='name', max_length=200)),
                ('place16', models.TextField(default='name')),
                ('place17', models.CharField(default='name', max_length=200)),
                ('place18', models.TextField(default='name')),
                ('place19', models.CharField(default='name', max_length=200)),
                ('place20', models.TextField(default='name')),
                ('place21', models.CharField(default='name', max_length=200)),
                ('place22', models.TextField(default='name')),
                ('place23', models.CharField(default='name', max_length=200)),
                ('place24', models.TextField(default='name')),
                ('place25', models.CharField(default='name', max_length=200)),
                ('place26', models.TextField(default='name')),
                ('place27', models.CharField(default='name', max_length=200)),
                ('place28', models.TextField(default='name')),
                ('place29', models.CharField(default='name', max_length=200)),
                ('place30', models.TextField(default='name')),
                ('place31', models.CharField(default='name', max_length=200)),
                ('Image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.image')),
            ],
        ),
        migrations.DeleteModel(
            name='Details1',
        ),
        migrations.AddField(
            model_name='details',
            name='place17',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='place18',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='details',
            name='place19',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='place20',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='details',
            name='place21',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='place22',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='details',
            name='place23',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='place24',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='details',
            name='place25',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='place26',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='details',
            name='place27',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='place28',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='details',
            name='place29',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='place30',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='details',
            name='place31',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
