# Generated by Django 5.1.3 on 2024-12-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0066_i_image_status_image_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('international', models.ImageField(upload_to='pic')),
                ('plan', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
