from django.contrib import admin
from.models import *

# Register your models here.
admin.site.register(Contact)
admin.site.register(Book)
admin.site.register(Image)
admin.site.register(i_Image)
admin.site.register(G_winder)
admin.site.register(G_summer)
admin.site.register(G_reserved)
admin.site.register(India)
admin.site.register(North)
admin.site.register(Education)
admin.site.register(South)
admin.site.register(East)
admin.site.register(Europe)
admin.site.register(Honeymoon)
admin.site.register(Kerala)
admin.site.register(Shimla)
admin.site.register(Manali)
admin.site.register(Andaman)
admin.site.register(Munnar)
admin.site.register(Kodai)
admin.site.register(Ooty)
admin.site.register(Paris)
admin.site.register(Italy)
admin.site.register(Tailand)
admin.site.register(Australia)
admin.site.register(Details)
